#!/usr/bin/bash

PERCENTAGE=$(pmset -g batt | egrep '([0-9]+\%).*' -o --colour=auto | cut -f1 -d'%')
SOURCE=$(pmset -g batt | grep "'.*'" | sed "s/'//g" | cut -c 18-19)

echo $(cat <<-EOF
{
    "percentage": "$PERCENTAGE",
    "source": "$SOURCE"
}
EOF
)