#!/usr/bin/bash

SERVICES=$(networksetup -listnetworkserviceorder | grep 'Hardware Port')

while read line; do
    sname=$(echo $line | awk -F  "(, )|(: )|[)]" '{print $2}')
    sdev=$(echo $line | awk -F  "(, )|(: )|[)]" '{print $4}')

    if [ -n "$sdev" ]; then
        ifconfig $sdev 2>/dev/null | grep 'status: active' > /dev/null 2>&1
        rc="$?"
        if [ "$rc" -eq 0 ]; then
            CURRENT_SERVICE="$sname"
            break
        fi
    fi
done <<< "$(echo "$SERVICES")"

#!/usr/bin/bash

WIFI_STATUS=$(ifconfig en0 | grep status | cut -c 10-)
WIFI_SSID=$(networksetup -getairportnetwork en0 | cut -c 24-)
IP_ADDRESS=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')

echo $(cat <<-EOF
{

    "service": "$CURRENT_SERVICE",
    "status": "$WIFI_STATUS",
    "ssid": "$WIFI_SSID",
    "ip": "$IP_ADDRESS"
}
EOF
)

